version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hackathon
      POSTGRES_USER: hackathon
      POSTGRES_DB: hackathon
    ports:
      - 5432:5432